# Generated by Django 5.0 on 2023-12-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cv',
            field=models.FileField(null=True, upload_to='assets/files/'),
        ),
    ]
