# Generated by Django 5.0 on 2023-12-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='questionnaireName',
            field=models.CharField(default='', max_length=45),
        ),
    ]
