# Generated by Django 5.0 on 2023-12-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_alter_option_id_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
    ]
